import { Injectable, NotFoundException } from '@nestjs/common';
import { SarychDBService } from '../SarychDB';

export interface CreateAdDto {
  name: string;
  type: 'image' | 'html';
  content: string;
  styles?: string;
  targetUrl: string;
  width?: number;
  height?: number;
}

export interface UpdateAdDto {
  name?: string;
  type?: 'image' | 'html';
  content?: string;
  styles?: string;
  targetUrl?: string;
  width?: number;
  height?: number;
  active?: boolean;
}

@Injectable()
export class AdsService {
  constructor(private readonly db: SarychDBService) {}

  async findAll(username: string, password: string) {
    const result = await this.db.browse(username, password, 'ads', 1, 1000);
    return result.data || [];
  }

  async findOne(username: string, password: string, id: string) {
    const result = await this.db.get(username, password, 'ads', id);
    const ads = result.results || [];
    const ad = ads.find((a: any) => a._id === id);
    if (!ad) throw new NotFoundException('Ad not found');
    return ad;
  }

  async create(username: string, password: string, dto: CreateAdDto) {
    const ad = {
      name: dto.name,
      type: dto.type,
      content: dto.content,
      styles: dto.styles || '',
      targetUrl: dto.targetUrl,
      width: dto.width || 728,
      height: dto.height || 90,
      active: true,
      impressions: 0,
      clicks: 0,
    };

    const result = await this.db.post(username, password, 'ads', ad);

    // The inserted record's _id is generated by SarychDB.
    // We need to find it so we can register it in the public registry.
    // SarychDB post doesn't return the id, so we search for it by name.
    try {
      const all = await this.db.browse(username, password, 'ads', 1, 1000);
      const records: any[] = all.data || [];
      // Find the most recently created ad with this name
      const sorted = records
        .filter((r: any) => r.name === dto.name)
        .sort((a: any, b: any) => (b._created_at || '').localeCompare(a._created_at || ''));
      if (sorted.length > 0) {
        await this.db.registerAd(sorted[0]._id, username, password);
      }
    } catch (e: any) {
      // Registration failure shouldn't block ad creation
    }

    return result;
  }

  async update(username: string, password: string, id: string, dto: UpdateAdDto) {
    const updateData: any = { _id: id, ...dto };
    return this.db.edit(username, password, 'ads', updateData);
  }

  async remove(username: string, password: string, id: string) {
    // Remove from public registry first
    await this.db.unregisterAd(id);
    return this.db.deleteById(username, password, 'ads', id);
  }

  async getEmbedData(username: string, password: string, id: string) {
    const ad = await this.findOne(username, password, id);
    return {
      id: ad._id,
      type: ad.type,
      content: ad.content,
      styles: ad.styles,
      targetUrl: ad.targetUrl,
      width: ad.width,
      height: ad.height,
    };
  }
}
